title: Huilin Yin's Homepage
page-top-title: Huilin Yin
top-section-bg-text: Computer Science
home-subtitle: Huilin Yin&ensp;|&ensp;殷慧琳
copyright-text: '&copy; Huilin Yin 2023-2026. All Rights Reserved.'
